about/urls.py
from django.urls import path
from .views import aboutt

app_name = 'about'

urlpatterns = [
    path('acercade/', aboutt, name="about")
]

grafo/urls.py
from django.urls import path
from django.urls.conf import path
from .views import generaGrafo,procesamiento
urlpatterns = [

    path('grafo/',generaGrafo, name='grafo'),
    path('procesamiento/',procesamiento, name='procesamiento'),

    # path('procesamiento/',procesamiento, name='procesamiento'),
]

home/urls.py
from django.urls.conf import path
from .views import home,procesamiento
from . import views
urlpatterns = [
    path('',home, name='home'),
    path('procesamiento/',procesamiento, name='procesamiento'),
    # con el <int:pk>le decimos que a la  pagina necesita un numero de tipo entero para poder avanzar 
]

proyectoHolaMundo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('sintactico.urls')),
    path('', include('about.urls')),
    path('', include('grafo.urls')),
]

sintactico/urls.py
from django.urls import path, re_path
from .views import principall

app_name = 'Sintactico'

urlpatterns = [
    path('sin/', principall, name='patrones'),
    path('about/', principall, name='about'),
    path('grafos/', principall, name='grafos'),
    path('home/', principall, name='home'),
]

about/models.py
from django.db import models

# Create your models here.

grafo/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class paciente(models.Model):

    Nombre = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"
    
    def __str__(self):
        return self.Nombre
    
    # def get_absolute_url(self):
    #     return reverse("Paciente_detail", kwargs={"pk": self.pk})

class tessiu(models.Model): #Herencia

    Temperatura = models.FloatField(verbose_name="Temperatura")
    Color = models.FloatField()
    Inflamation = models.FloatField(verbose_name="Inflamacion")
    #el blank y el null son espacios donde pueden ir nulos
    Nombre = models.ForeignKey(paciente, on_delete=models.CASCADE,blank=True, null=True)

    class Meta:
        verbose_name = "tejido"
        verbose_name_plural = "Tejidos"

    def __str__(self):
        # es la forma en la que se va a imprimir 
        return 'Temperatura '+str(self.Temperatura)+' Color '+str(self.Color) 


    # def get_absolute_url(self): no tiene uso 
    #     return reverse("tablaValores_detail", kwargs={"pk": self.pk})


    

sintactico/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def aboutt(request):
    resultado =mifuncion(request)
    template_name ='templates/about/about.html'
    # dict={"nombreusuario":resultado, 'edad':20}
    return render(request, template_name, )

def mifuncion(args):
    return 'Giovanny'


    #maneras de imprimir en html
    #return HttpResponse('<h1>About</h1><li>Hola</li>')
    # txtHtml="""
    # <h1>Hola</h1>
    # <li>Donde</li>
    # <li>la fiesta</li>
    # """
    # return HttpResponse(txtHtml)

grafo/views.py
import numpy as np
from django.http import request
from django.shortcuts import render
from home.models import tessiu
import math
# Create your views here.


def generaGrafo(request):
    lista = tessiu.objects.get_queryset()
    template_name='templates/grafo/grafo.html'
    diccionario={}
    calcula(lista)
    return render(request, template_name, diccionario)

def calcula (L):
    n=np.array([1,2,3])
    return n
def procesamiento (request):
    UMBRAL=0
    if request.method == 'GET':
        UMBRAL=int(request.GET.get('umbral'))

    print('me mandaste el ',UMBRAL)
    lista = tessiu.objects.get_queryset()
    # L1,L2 =procesalista(lista)
    elementos=len(lista)
    ca=CalculeDistancias(lista,elementos)
    tabla=conectaGrafo(lista,UMBRAL,elementos)
    template_name='templates/grafo/grafo.html' 
    diccionario={'ca':ca,'tabla':tabla}
    return render(request, template_name, diccionario)

def CalculeDistancias(L,el):
    # df=pd.DataFrame(L)
    # L=[{'r1':j,'r2':i ,'conectado':'si'if math.sqrt((df[j:2:el])**2+(df[i:2:el])**2)<= el else 'no'}for j in range(0,el)for i in range(j+1,el)]
    MatrizDis=[]

    for el in L:
        distancia=math.sqrt(el.Temperatura**2+el.Color**2)
        MatrizDis.append(el)
        
    return MatrizDis
def conectaGrafo(L,Um,el):
    MatrizUm=[]
    for el in L:
        distancia=math.sqrt(el.Temperatura**2+el.Color**2)
        if distancia <= Um :
            MatrizUm.append(el)
    return MatrizUm

# request es la peticion desde el navegador   
# def procesamiento (request):
#     print("Hola")

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import tessiu
import math 
# Create your views here.

def home(request):
    lista = tessiu.objects.get_queryset()
    L1,L2 =procesalista(lista)
    template_name='templates/home/home.html'
    mislistas = [lista,L1,L2]
    diccionario={'lista':lista,"otra":"Informaciòn","L1":L1,"L2":L2,"MISLISTAS":mislistas}
    return render(request, template_name, diccionario)

def procesalista(L):
    listaColorMayor20=[]
    listaColorMenor20=[]
    for i in L:
        if i.Color > 20:
            listaColorMayor20.append(i)
        else:
            listaColorMenor20.append(i)

    return listaColorMayor20,listaColorMenor20
    #return HttpResponse('<h1>Hola Mundo</h1><li>Hola</li>')
def procesamiento (request):
    UMBRAL=0
    if request.method == 'GET':
        UMBRAL=int(request.GET.get('umbral'))

    print('me mandaste el ',UMBRAL)
    lista = tessiu.objects.get_queryset()
    # L1,L2 =procesalista(lista)
    elementos=len(lista)
    ca=CalculeDistancias(lista,elementos)
    tabla=conectaGrafo(lista,UMBRAL,elementos)
    template_name='templates/grafo/grafo.html' 
    diccionario={'ca':ca,'tabla':tabla}
    return render(request, template_name, diccionario)

def CalculeDistancias(L,el):
    # df=pd.DataFrame(L)
    # L=[{'r1':j,'r2':i ,'conectado':'si'if math.sqrt((df[j:2:el])**2+(df[i:2:el])**2)<= el else 'no'}for j in range(0,el)for i in range(j+1,el)]
    MatrizDis=[]

    for el in L:
        distancia=math.sqrt(el.Temperatura**2+el.Color**2)
        MatrizDis.append(el)
        
    return MatrizDis
def conectaGrafo(L,Um,el):
    MatrizUm=[]
    for el in L:
        distancia=math.sqrt(el.Temperatura**2+el.Color**2)
        if distancia <= Um :
            MatrizUm.append(el)
    return MatrizUm

sintactico/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def principall(request):
    template_name ='templates/sin/s.html'
    diccionariocontenido={'lista':[1,2,3,4,5]}
    return render(request, template_name, diccionariocontenido)

# def principal(request):
#     return HttpResponse('<h1>Sintactico Estructural</h1><li>Hola</li>')

about/templates/about/about.html
{% extends 'templates/home/home.html' %}{% block contenido %}
<h1>Jugadores mas importantes en la UEFA Champions League</h1>
<!-- <h2>Mi nombre de usuario es: {{nombreusuario}}</h2>
<h3>Mi edad es: {{edad}}</h3> -->
<body>
    <div class="con">
        <div class="galeria">
        <div class="foto">
            <img src="https://media.infocielo.com/p/7ff5b6ed613cc324a1add6ae0bfad55a/adjuntos/299/imagenes/001/247/0001247700/1200x900/smart/messi-argentina-festejojpg.jpg" class="foto1">
        </div>
        <div class="pie">
            <p>Messi</p>
            <p>Argentina</p>
        </div>
    </div>
    <div class="galeria">
        <div class="foto">
            <img src="https://thumbs.dreamstime.com/b/futbolista-brasile%C3%B1o-neymar-jr-mosc%C3%BA-rusia-de-junio-superestrella-brasile%C3%B1a-antes-del-partido-la-copa-mundial-fifa-serbia-vs-167538942.jpg" class="foto1">
        </div>
        <div class="pie">
            <p>NeymarJR</p>
            <p>Brasil</p>
        </div>
    </div>
    <div class="galeria">
        <div class="foto">
            <img src="https://www.revistacambio.com.mx/wp-content/uploads/2020/02/Cistiano-.jpg" class="foto1">
        </div>
        <div class="pie">
            <p>Cristiano Ronaldo</p>
            <p>Portugal</p>
        </div>
    </div>
    <div class="galeria">
        <div class="foto">
            <img src="https://www.futbolred.com/files/article_main/files/crop/uploads/2020/09/05/5f54035190860.r_1636759520652.0-68-2240-1187.jpeg" class="foto1">
        </div>
        <div class="pie">
            <p>Kylian Mbappe</p>
            <p>Francia</p>
        </div>
    </div>
    <div class="galeria">
        <div class="foto">
            <img src="https://i.pinimg.com/originals/4c/77/63/4c77633b614eee02aa001e0da9c2685f.jpg" class="foto1">
        </div>
        <div class="pie">
            <p>Robert Lewandowski</p>
            <p>Polonia</p>
        </div>
    </div>
    <div class="galeria">
        <div class="foto">
            <img src="https://3.bp.blogspot.com/-geCVn8wyvOA/WzCu6bAFp-I/AAAAAAAAK2U/fDo6gTfQJ0gLFaaR5akr9CxOK2akze-SQCLcBGAs/w1200-h630-p-k-no-nu/camiseta_belgica_De_Bruyne_2018%2B%25286%2529.png" class="foto1">
        </div>
        <div class="pie">
            <p>Kevin De Bruyne</p>
            <p>Belgica</p>
        </div>
    </div>
    </div>
    
</body>
{% endblock contenido %}

grafo/templates/grafo/grafo.html
{% extends 'templates/home/home.html' %}
<body>
    {% block contenido %}

<p>Ingresa un umbral para poder calcular las distancias </p>
<br>
<br>
<form action="{% url  'procesamiento'  %}" method="get">
    {% csrf_token %}
    <label for="umbral">Umbral</label>
    <input type="text"name="umbral" id="umbral">
<button type="submit" name="miboton">Iniciar Procesamiento</button>
</form>
<br>
<br>
<br>
<ul>
    <h1>Matriz de distancias</h1>
    <table>
        <thead>
            <tr>
                <td style="border: 2px dotted rgb(0, 140, 255);">Distancias</td>
            </tr>
        </thead>
        <tbody>
            {% for elementos in ca %}
            <tr>
                <td style="border: 2px dotted rgb(0, 140, 255);">{{elementos}}</td>
            </tr>
           
            {% endfor %}
        </tbody>
    </table>
    <br>
</ul>
<ul>
    <h1>Matriz de distancias dependiendo el Umbral</h1>
    <table>
        <thead>
            <tr>
                <td style="border: 2px dotted rgb(0, 140, 255);">Distancias</td>
            </tr>
        </thead>
        <tbody>
            {% for elementos in tabla %}
            <tr>
                <td style="border: 2px dotted rgb(0, 140, 255);">{{elementos}}</td>
            </tr>
           
            {% endfor %}
        </tbody>
    </table>
    <br>
</ul>   
{% endblock contenido %}
</body>

home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


<link rel="stylesheet" href="{% static 'static/css/style2.css'%}">
<link rel="icon" href="https://img.uefa.com/imgml/favicon/comp/ucl.ico">
    <title>Pagina Principal</title>
</head>
<!-- Menu sencillo -->
<body>
    <!-- <header> -->
        <!-- <nav class="navegador">
            <ul class="Menu">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'Sintactico:patrones' %}">Sintactico</a></li>
                <li><a href="{% url  'grafo' %}">Grafos</a></li>
                <li><a href="{% url  'about:about' %}">Acerca De</a></li>
            </ul>
        </nav> -->
        <!-- <div class="navbar">MENU
            <ul class="menu">
                <li><a href="{% url 'home' %}" class="h"><img src="https://cdn-icons-png.flaticon.com/512/553/553376.png" alt="" class="icono"></a></li>
                <li><a href="{% url 'Sintactico:patrones' %}" class="s"></a></li>
                <li><a href="{% url  'grafo' %}" class="g"></a></li>
                <li><a href="{% url  'about:about' %}" class="a"></a></li>
            </ul>
        </div> -->
    <!-- </header> -->
    <header>
        <div class="contenedor" id="uno">
            <a href="{% url 'home' %}" ><img src="https://cdn-icons-png.flaticon.com/512/553/553376.png" class="icono"></a><p class="texto">Home</p>
        </div>
        <div class="contenedor" id="dos">
            <a href="{% url 'Sintactico:patrones' %}" ><img src="https://cdn-icons.flaticon.com/png/512/3494/premium/3494579.png" class="icono"></a><p class="texto">Informaciòn</p>
        </div>
        <div class="contenedor" id="tres">
            <a href="{% url  'grafo' %}" ><img src="https://cdn-icons-png.flaticon.com/512/4525/4525943.png" class="icono"></a><p class="texto">Grafo</p>
        </div>
        <div class="contenedor" id="cuatro">
            <a href="{% url  'about:about' %}" ><img src="https://cdn-icons-png.flaticon.com/512/16/16410.png" class="icono"></a><p class="texto">Galeria</p>
        </div>
    </header>
    {% block contenido %}
    <!-- <form action="{% url  'procesamiento'  %}" method="get">
        {% csrf_token %}
        <label for="umbral">Umbral</label>
        <input type="text"name="umbral" id="umbral">
    <button type="submit" name="miboton">Iniciar Procesamiento</button>
</form> -->
    <!-- <img src="https://wallpapersflix.com/wp-content/uploads/2021/08/Lionel-Messi-PSG-Wallpaper-HD.jpg" class="ImgP"> -->
    
<!--     
     1er tipo de imprimir consultas 
    {{lista}}
    2do tipo de imprimir consultas 
    <ul>
        {% for elemento in lista %}
        <li>{{elemento}}</li>
        {% endfor %}
    </ul>
    Consulta especifica 
    <ul>
        <h1>Consulta Especifica</h1>
        {% for elemento in lista %}
        <li>{{elemento.Temperatura }}--{{elemento.Color}}--{{elemento.Inflamation}}</li>
        {% endfor %}
    </ul> -->
    <!--Consulta en tabla  -->
    
        

     
    <ul>
        <h1>Consulta en tabla</h1>
        <table>
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Temperatura</td>
                    <td>Color</td>
                    <td>Inflamacion</td>
                </tr>
            </thead>
            <tbody>
                {% for elemento in lista %}
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">{{elemento.pk}}</td>
                    <td style="border: 2px dotted black;">{{elemento.Temperatura }}</td>
                    <td style="border: 2px solid green;">{{elemento.Color}}</td>
                    <td style="border: 2px dotted red;">{{elemento.Inflamation}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </ul>
    <!-- -------------------------Filto------------------ -->
    <ul>
        <h1>Consulta en tabla Filtro</h1>
        <p>Lista -----> Color menor a 20</p>
        <table>
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Temperatura</td>
                    <td>Color</td>
                    <td>Inflamacion</td>
                </tr>
            </thead>
            <tbody>
                {% for elemento in L2 %}
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">{{elemento.pk}}</td>
                    <td style="border: 2px dotted black;">{{elemento.Temperatura }}</td>
                    <td style="border: 2px solid green;">{{elemento.Color}}</td>
                    <td style="border: 2px dotted red;">{{elemento.Inflamation}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </ul>
    <ul>
        <h1>Consulta en tabla Filtro</h1>
        <p>Lista -----> Color mayor a 20</p>
        <table>
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Temperatura</td>
                    <td>Color</td>
                    <td>Inflamacion</td>
                </tr>
            </thead>
            <tbody>
                {% for elemento in L1 %}
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">{{elemento.pk}}</td>
                    <td style="border: 2px dotted black;">{{elemento.Temperatura }}</td>
                    <td style="border: 2px solid green;">{{elemento.Color}}</td>
                    <td style="border: 2px dotted red;">{{elemento.Inflamation}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </ul>
    <!-- PARA NO REPETIR EL MISMO CODIGO TRES VECES CON LOS FILTROS  -->
    <ul>
        <h1>Consulta en tabla 1 VEZ PARA LAS 3 LISTAS</h1>
        <p>3 Listas</p>

        {% for lista in MISLISTAS %}

        <table>
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Temperatura</td>
                    <td>Color</td>
                    <td>Inflamacion</td>
                </tr>
            </thead>
            <tbody>
                {% for elemento in lista %}
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">{{elemento.pk}}</td>
                    <!-- CONDICION PARA VER CUAL ESTA ABAJO DE 20 DE UN COLOR  -->

                    {% if elemento.Temperatura < 20 %}
                    <td style="border: 2px dotted black;">{{elemento.Temperatura }}</td>
                    {% else %}
                    <td style="border: 2px dotted rgb(111, 0, 255);">{{elemento.Temperatura }}</td>
                    {% endif %}
                    <td style="border: 2px solid green;">{{elemento.Color}}</td>
                    <td style="border: 2px dotted red;">{{elemento.Inflamation}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    </ul>
    {% endfor %}
  <!-- <p>-------------------------Prueba------------------</p>
    <ul>
        <h1>Matriz de distancias</h1>
        <table>
            <thead>
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">Distancias</td>
                </tr>
            </thead>
            <tbody>
                {% for elementos in ca %}
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">{{elementos}}</td>
                </tr>
               
                {% endfor %}
            </tbody>
        </table>
        <br>
    </ul>
    <p>-------------------------Prueba2------------------</p>
    <ul>
        <h1>Matriz de distancias dependiendo el Umbral</h1>
        <table>
            <thead>
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">Distancias</td>
                </tr>
            </thead>
            <tbody>
                {% for elementos in tabla %}
                <tr>
                    <td style="border: 2px dotted rgb(0, 140, 255);">{{elementos}}</td>
                </tr>
               
                {% endfor %}
            </tbody>
        </table>
        <br>
    </ul> -->
    <footer>
        <h2>UEFA Champions League</h2>
        <div class="fo">
            <a href="https://www.facebook.com/ChampionsLeague/"><img src="https://cdn-icons.flaticon.com/png/512/3665/premium/3665895.png?token=exp=1638163663~hmac=6a378d9e1b93533b7dfaf2cfa34d1766" class="redes"></a>
            <a href="https://www.instagram.com/championsleague/"><img src="https://cdn-icons-png.flaticon.com/512/1419/1419647.png" class="redes"></a>
            <a href="https://twitter.com/UEFAcom_es"><img src="https://cdn-icons-png.flaticon.com/512/25/25347.png" class="redes"></a>
        </div>
    </footer>
    {% endblock contenido %}
</body>
</html>

sintactico/templates/sin/s.html
{% extends 'templates/home/home.html' %}<body>{% block contenido %}
<br>
<h1></h1>

    <div class="Contenedor">
        <div class="uno">
            <h1>Informacion General</h1>
            <p class="info">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime dolorem molestiae placeat at laudantium consequuntur quia optio itaque eos asperiores deserunt, saepe laborum tenetur nisi aut. Eveniet ea nemo quia.</p>
        </div>
        <div class="dos">
            <h1>Reglas</h1>
            <p class="info">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur impedit aperiam assumenda mollitia accusamus officia provident modi dicta ex cum! Voluptatum quasi reiciendis accusamus, alias labore quisquam eveniet qui aspernatur.</p>
        </div>
        <div class="tres">
            <h1>Maximos Goleadores de la UEFA Champions League</h1>
            <br>
            <table>
                <tr>
                    <th>Nombre</th>
                    <th>Equipo</th>
                    <th>Goles</th>
                </tr>
                <tr>
                    <td>Cristiano Ronaldo</td>
                    <td>Manchester United</td>
                    <td>140</td>
                </tr>
                <tr>
                    <td>Lionel Messi</td>
                    <td>Paris Saint-Germain</td>
                    <td>123</td>
                </tr>
                <tr>
                    <td>Robert Lewandowski</td>
                    <td>Bayern Mùnich</td>
                    <td>82</td>
                </tr>
                <tr>
                    <td>Karim Benzema</td>
                    <td>Real Madrid</td>
                    <td>76</td>
                </tr>
            </table>
        </div>
        <div class="cuatro">
            <h1>Trofeo</h1>
            <br>
            <img src="https://www.ustedpregunta.com/data/articulos/que-equipos-tienen-en-propiedad-la-copa-de-la-champions-league/5db6b996d987d.jpg" class="trofeo">
        </div>
    </div>
{% endblock contenido %}
</body>